version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
